apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /export/kubernetes-pv
    server: 192.168.121.1
