apiVersion: v1
kind: ConfigMap
metadata:
  name: openvswitch-db-server-kolla-config
  namespace: default
  labels:
    service: openvswitch-db-server
data:
  config.json: |
    {
        "command": "start-ovsdb-server 127.0.0.1"
    }
