apiVersion: v1
kind: ConfigMap
metadata:
  name: openvswitch-db-server-kolla-config
  namespace: default
  labels:
    service: openvswitch-db-server
data:
  config.json: |
    {
        "command": "ovsdb-server /etc/openvswitch/conf.db -vconsole:info --remote=punix:/var/run/openvswitch/db.sock --remote=ptcp:6640:0.0.0.0"
    }
