apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: openvswitch-db-server
spec:
  template:
    metadata:
      labels:
        app: openvswitch-db-server
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
             "name": "openvswitch-db-server-bootstrap",
             "image": "tripleoupstream/centos-binary-openvswitch-db-server",
             "imagePullPolicy": "Always",
             "command": ["/usr/bin/ovsdb-tool", "create", "/etc/openvswitch/conf.db"],
             "volumeMounts": [
                {
                   "name": "etc-openvswitch",
                   "mountPath": "/etc/openvswitch"
                }
             ]
          }
        ]'
    spec:
      nodeSelector:
        tripleo/service-l2-agent: "true"
      hostNetwork: true
      hostIPC: true
      containers:
        - name: openvswitch-db-server
          image: tripleoupstream/centos-binary-openvswitch-db-server
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          volumeMounts:
            - name: kolla-config
              mountPath: /var/lib/kolla/config_files/
            - name: etc-openvswitch
              mountPath: /etc/openvswitch
            - name: host-run-openvswitch
              mountPath: /var/run/openvswitch
            - name: host-dev
              mountPath: /dev
      volumes:
        - name: kolla-config
          configMap:
            name: openvswitch-db-server-kolla-config
        - name: etc-openvswitch
          emptyDir: {}
        - name: host-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: host-dev
          hostPath:
            path: /dev
