apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-ovs-agent
spec:
  template:
    metadata:
      labels:
        app: neutron-ovs-agent
      annotations:
        # eventually we'd at least mount the script in,
        # to prevent so much escaping
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "local-conf",
            "image": "tripleoupstream/centos-binary-neutron-openvswitch-agent",
            "imagePullPolicy": "Always",
            "command": ["bash", "-c"],
            "args": ["
              DEFAULT_ROUTE_DEV=$(ip r | grep ''^default'' | grep -oE ''dev ([^ ]+)'' | awk ''{ print $2; }'');
              LOCAL_IP=$(ip a show $DEFAULT_ROUTE_DEV | grep ''^ *inet '' | awk ''{ print $2; }'' | awk -F/ ''{ print $1; }'');
              cat > /var/lib/neutron/local/local.conf <<EOF\n[ovs]\nlocal_ip=$LOCAL_IP\nEOF\n
              "
            ],
            "volumeMounts": [
              {
                "mountPath": "/var/lib/neutron/local",
                "name": "neutron-local"
              }
            ]
          },
          {
            "name": "ovs-socket-ownership",
            "image": "tripleoupstream/centos-binary-neutron-openvswitch-agent",
            "imagePullPolicy": "Always",
            "command": ["chown", "neutron:", "/run/openvswitch/db.sock"],
            "securityContext": {
              "runAsUser": 0
            },
            "volumeMounts": [
              {
                "mountPath": "/run",
                "name": "host-run"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        tripleo/service-l2-agent: "true"
      # currently ClusterFirst doesn't work with hostNetwork
      # for now we also mount resolv.conf from configmap
      # https://github.com/kubernetes/kubernetes/issues/17406
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: neutron-ovs-agent
          image: tripleoupstream/centos-binary-neutron-openvswitch-agent
          securityContext:
            privileged: true
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          volumeMounts:
            - name: kolla-config
              mountPath: /var/lib/kolla/config_files/
            - name: host-dev
              mountPath: /dev
            - name: host-lib-modules
              mountPath: /lib/modules
            # TODO: mount this as ':shared' so that network namespaces
            # propagate, no k8s support ATM
            - name: host-run
              mountPath: /run
            - name: neutron-local
              mountPath: /var/lib/neutron/local
            - name: resolv-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
              readOnly: true
      volumes:
        - name: kolla-config
          configMap:
            name: neutron-ovs-agent-kolla-config
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
        - name: host-run
          hostPath:
            path: /run
        - name: resolv-conf
          configMap:
            name: resolv-conf
        - name: neutron-local
          emptyDir: {}
