apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: tripleoupstream/centos-binary-rabbitmq:latest
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - name: rabbitmq-kolla-config
              mountPath: /var/lib/kolla/config_files
      volumes:
        - name: rabbitmq-kolla-config
          configMap:
            name: rabbitmq-kolla-config
            items:
              - key: kolla-config
                path: config.json
