apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      nodeSelector:
        tripleo/role-generic: "true"
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: tripleoupstream/centos-binary-rabbitmq:latest
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - name: rabbitmq-kolla-config
              mountPath: /var/lib/kolla/config_files
            - name: rabbitmq-pvc
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-kolla-config
          configMap:
            name: rabbitmq-kolla-config
            items:
              - key: kolla-config
                path: config.json
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-pvc
        annotations:
          volume.beta.kubernetes.io/storage-class: "slow"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
