apiVersion: v1
data:
  kolla-config: |
    {
        "command": "/usr/bin/mysqld_safe",
        "config_files": []
    }
  my-cnf: |
    [client-server]
    !includedir /etc/my.cnf.d
kind: ConfigMap
metadata:
  name: mariadb-kolla-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/mariadb-kolla-config
