apiVersion: v1
data:
  kolla-config: |
    {
        "command": "/usr/bin/mysqld_safe",
        "config_files": []
    }
  server-cnf: |
    [mysqld]
    pid-file=/var/lib/mysql/mariadb.pid
kind: ConfigMap
metadata:
  name: mariadb-kolla-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/mariadb-kolla-config
