apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql 
spec:
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: tripleoupstream/centos-binary-mariadb 
        ports:
        - containerPort: 3306
          name: mysql 
        volumeMounts:
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
