apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql 
spec:
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: tripleoupstream/centos-binary-mariadb 
        ports:
        - containerPort: 3306
          name: mysql 
        volumeMounts:
        - name: kolla-config 
          mountPath: /var/lib/kolla/config_files/
        - name: mysql-config 
          mountPath: /etc/mysql/
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: kolla-config
          configMap:
            name: mariadb-kolla-config
            items:
            - key: kolla-config
              path: config.json
        - name: mysql-config 
          configMap:
            name: mariadb-kolla-config
            items:
            - key: my-cnf 
              path: my.cnf
