apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-api-kolla-config
  namespace: default
  labels:
    service: nova-api
data:
  config.json: |
    {
        "command": "nova-api",
        "config_files": [
          {
            "dest": "/etc/nova/nova.conf",
            "owner": "nova",
            "perm": "0644",
            "source": "/var/lib/kolla/config_files/nova.conf"
          }
        ]
    }
  nova.conf: |
    [DEFAULT]
    bind_host = 0.0.0.0
    rabbit_host = rabbitmq
    use_neutron = True

    # This probably needs to be changed to non-null, but with the
    # default i'm getting errors when nova tries to run
    # 'sudo nova-rootwrap /etc/nova/rootwrap.conf iptables-save -c'
    # l3_lib = nova.network.l3.NullL3
    # firewall_driver = nova.virt.firewall.NoopFirewallDriver
    # linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver
    [database]
    connection=mysql+pymysql://root:weakpassword@mariadb:3306/nova
    [api_database]
    connection=mysql+pymysql://root:weakpassword@mariadb:3306/nova_api
    [keystone_authtoken]
    auth_host = keystone-admin
    auth_port = 35357
    auth_protocol = http
    admin_tenant_name = admin
    admin_user = admin
    admin_password = weakpassword
