apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nova-api
    spec:
      nodeSelector:
        tripleo/role-generic: "true"
      containers:
        - name: nova-api
          image: tripleoupstream/centos-binary-nova-api
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          ports:
            - containerPort: 8774
              name: nova-api
          volumeMounts:
            - name: kolla-config
              mountPath: /var/lib/kolla/config_files/
          securityContext:
            # seems to be needed otherwise nova-api fails to run
            # `sudo nova-rootwrap /etc/nova/rootwrap.conf iptables-save -c`
            # and fails to start up
            privileged: true
      volumes:
        - name: kolla-config
          configMap:
            name: nova-api-kolla-config
