apiVersion: batch/v1
kind: Job
metadata:
  name: nova-db-create
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: tripleoupstream/centos-binary-mariadb
          name: nova-db-create
          command:
            - mysql
            - -h
            - mariadb
            - -u
            - root
            - --password=weakpassword
            - -e
            - create database nova;
        - image: tripleoupstream/centos-binary-mariadb
          name: nova-api-db-create
          command:
            - mysql
            - -h
            - mariadb
            - -u
            - root
            - --password=weakpassword
            - -e
            - create database nova_api;
