apiVersion: batch/v1
kind: Job
metadata:
  name: glance-db-sync
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "glance-db-create",
            "image": "tripleoupstream/centos-binary-mariadb",
            "imagePullPolicy": "Always",
            "command": [
              "mysql",
              "-h",
              "mariadb",
              "-u",
              "root",
              "--password=weakpassword",
              "-e",
              "create database glance;"
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - image: tripleoupstream/centos-binary-glance-api
          name: glance-db-sync
          command: ['glance-manage', '--config-file', '/etc/glance/glance-api.conf', 'db_sync']
          volumeMounts:
            - name: kolla-config
              mountPath: /var/lib/kolla/config_files/
            - name: glance-api-config
              mountPath: /etc/glance/
      volumes:
        - name: kolla-config
          configMap:
            name: glance-api-kolla-config
            items:
            - key: kolla-config
              path: config.json
        - name: glance-api-config
          configMap:
            name: glance-api-kolla-config
            items:
            - key: glance-api-conf
              path: glance-api.conf
