apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: glance-api 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glance-api 
    spec:
      nodeSelector:
        tripleo/role-generic: "true"
      containers:
      - name: glance-api 
        image: tripleoupstream/centos-binary-glance-api
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
        ports:
        - containerPort: 9292 
          name: glance-api 
        volumeMounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
        - name: glance-api-config
          mountPath: /etc/glance/
      volumes:
        - name: kolla-config
          configMap:
            name: glance-api-kolla-config
            items:
            - key: kolla-config
              path: config.json
        - name: glance-api-config
          configMap:
            name: glance-api-kolla-config
            items:
            - key: glance-api-conf
              path: glance-api.conf
