kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glance-api-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
