apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "bootstrap",
            "image": "tripleoupstream/centos-binary-mariadb",
            "env": [
              {
                "name": "KOLLA_KUBERNETES",
                "value": ""
              },
              {
                "name": "KOLLA_BOOTSTRAP",
                "value": ""
              },
              {
                "name": "KOLLA_CONFIG_STRATEGY",
                "value": "COPY_ALWAYS"
              },
              {
                "name": "DB_ROOT_PASSWORD",
                "value": "weakpassword"
              }
            ],
            "volumeMounts": [
              {
                "name": "kolla-config",
                "mountPath": "/var/lib/kolla/config_files/"
              },
              {
                "name": "mariadb-config",
                "mountPath": "/etc/my.cnf.d"
              },
              {
                "name": "mariadb-pvc",
                "mountPath": "/var/lib/mysql"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        tripleo/role-generic: "true"
      containers:
      - name: mariadb
        image: tripleoupstream/centos-binary-mariadb
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
        - name: DB_ROOT_PASSWORD
          value: weakpassword
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
        - name: mariadb-config
          mountPath: /etc/my.cnf.d
        - name: mariadb-pvc
          mountPath: /var/lib/mysql
      volumes:
        - name: kolla-config
          configMap:
            name: mariadb-kolla-config
            items:
            - key: kolla-config
              path: config.json
        - name: mariadb-config
          configMap:
            name: mariadb-kolla-config
            items:
            - key: server-cnf
              path: server.cnf
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
        annotations:
          volume.beta.kubernetes.io/storage-class: "slow"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
